# Site settings
title: Home
site: DGG
footer: Contact Info
social: Social Media
email_tag: Email
email: dhawangayash@gmail.com
disclaimer: Disclaimer
description: > # this means to ignore newlines until "baseurl:"
  A placeholder to keep all my current ideas and thoughts. This
  does not reflect my current or past employers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dhawangayash
github_username:  gitprouser
highlighter: pygments
# Build settings
markdown: kramdown
