# Site settings
title: "Dhawan Gayash's Blog"
description: "My thoughts on software engineering and beyond."
baseurl: "" 
url: "http://gitprouser.github.io"
tagline: "Fate is fluid, destiny is the hands of men."

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:year/:month/:day/:title.html
gems: [jekyll-paginate]